# Generated by Django 4.2 on 2024-02-21 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='_profile_images')),
                ('contact_number', models.CharField(default='+380123123123', max_length=50)),
            ],
        ),
    ]
