# Generated by Django 4.2 on 2024-02-22 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_reviews_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='product',
            new_name='product_id',
        ),
    ]
