# Generated by Django 4.2 on 2024-02-22 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_product_reviews_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='product_id',
            new_name='product',
        ),
    ]
